# Generated by Django 3.0.14 on 2022-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=100)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Created_by', models.CharField(max_length=100)),
                ('Project_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
