# Generated by Django 3.0.14 on 2022-12-20 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20221220_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Created_by',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Id',
            new_name='User_code',
        ),
        migrations.AddField(
            model_name='project',
            name='Created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
